import { I18nManager } from 'react-native';

const COPY = {
  back: ['Back', 'رجوع'],
  mobileTitle: ['Sign in with mobile number', 'تسجيل الدخول برقم الجوال'],
  mobileSubtitle: ['Enter the mobile number registered with your company.', 'أدخل رقم الجوال المسجل لدى شركتك.'],
  companySubtitle: ['Enter your company code and the mobile number registered with your company.', 'أدخل رمز الشركة ورقم الجوال المسجل لديها.'],
  serverSubtitle: ["Enter your company's server address and the mobile number registered with your company.", 'أدخل عنوان خادم الشركة ورقم الجوال المسجل لديها.'],
  selectedCompany: ['Company selected', 'تم اختيار الشركة'],
  change: ['Change', 'تغيير'],
  changeCompany: ['Change company', 'تغيير الشركة'],
  companyCode: ['Company code', 'رمز الشركة'],
  serverAddress: ['Server address', 'عنوان الخادم'],
  useCompanyCode: ['Use company code', 'استخدام رمز الشركة'],
  useServerAddress: ['Use server address', 'استخدام عنوان الخادم'],
  companyPlaceholder: ['Enter company code', 'أدخل رمز الشركة'],
  mobileNumber: ['Mobile number', 'رقم الجوال'],
  mobilePlaceholder: ['Enter mobile number', 'أدخل رقم الجوال'],
  continue: ['Continue', 'متابعة'],
  scanQr: ['Scan QR code', 'مسح رمز QR'],
  or: ['or', 'أو'],
  otpTitle: ['Verify your mobile number', 'تحقق من رقم جوالك'],
  otpSubtitle: [mobile => `We sent a verification code to ${mobile}.`, mobile => `أرسلنا رمز التحقق إلى ${mobile}.`],
  otpNotSent: [mobile => `Enter the verification code for ${mobile}.`, mobile => `أدخل رمز التحقق الخاص بالرقم ${mobile}.`],
  verificationCode: ['Verification code', 'رمز التحقق'],
  codePlaceholder: ['Enter code', 'أدخل الرمز'],
  verifyCode: ['Verify code', 'تحقق من الرمز'],
  resendCode: ['Resend code', 'إعادة إرسال الرمز'],
  resendSeconds: [seconds => `Resend in ${seconds}s`, seconds => `إعادة الإرسال بعد ${seconds} ث`],
  signupOtpHint: ['Your code will be checked when you finish setting up your account.', 'سيتم التحقق من الرمز عند إكمال إعداد حسابك.'],
  recoveryOtpHint: ['Your code will be checked when you save your new password.', 'سيتم التحقق من الرمز عند حفظ كلمة المرور الجديدة.'],
  passwordTitle: ['Sign in with password', 'تسجيل الدخول بكلمة المرور'],
  passwordSubtitle: [mobile => `Sign in to the account for ${mobile}.`, mobile => `سجّل الدخول إلى حساب ${mobile}.`],
  password: ['Password', 'كلمة المرور'],
  passwordPlaceholder: ['Enter password', 'أدخل كلمة المرور'],
  signIn: ['Sign in', 'تسجيل الدخول'],
  forgotPassword: ['Forgot password?', 'نسيت كلمة المرور؟'],
  secureTitle: ['Secure your account', 'أمّن حسابك'],
  secureSubtitle: ['Create a password for easier sign-in next time. You can also skip this for now.', 'أنشئ كلمة مرور لتسهيل تسجيل الدخول لاحقًا. يمكنك أيضًا تخطي ذلك الآن.'],
  createTitle: ['Create a password', 'إنشاء كلمة مرور'],
  createPassword: ['Create password', 'إنشاء كلمة المرور'],
  createSubtitle: ['Create a password to finish setting up your account.', 'أنشئ كلمة مرور لإكمال إعداد حسابك.'],
  recoveryCreateSubtitle: ['Choose a password for your account. Your saved verification code will be checked when you continue.', 'اختر كلمة مرور لحسابك. سيتم التحقق من الرمز الذي أدخلته عند المتابعة.'],
  resetTitle: ['Reset password', 'إعادة تعيين كلمة المرور'],
  resetSubtitle: ['Choose a new password. Your saved verification code will be checked when you continue.', 'اختر كلمة مرور جديدة. سيتم التحقق من الرمز الذي أدخلته عند المتابعة.'],
  newPassword: ['New password', 'كلمة مرور جديدة'],
  passwordMinimum: ['At least 8 characters', '8 أحرف على الأقل'],
  confirmPassword: ['Confirm password', 'تأكيد كلمة المرور'],
  confirmPlaceholder: ['Re-enter password', 'أعد إدخال كلمة المرور'],
  skipPassword: ['Skip for now', 'تخطي الآن'],
  errorTitle: ['Sign-in could not finish', 'تعذّر إكمال تسجيل الدخول'],
  loading: ['Loading sign-in', 'جارٍ تحميل تسجيل الدخول'],
  completing: ['Signing you in', 'جارٍ تسجيل دخولك'],
  completingSubtitle: ['Finishing your account setup.', 'جارٍ إكمال إعداد حسابك.'],
  useQr: ['Use your QR code', 'استخدم رمز QR الخاص بك'],
  latestBuild: ['Mobile sign-in is available in the latest app build.', 'تسجيل الدخول بالجوال متاح في أحدث إصدار من التطبيق.'],
};

export function mobileLoginCopy(key, value) {
  const text = COPY[key][I18nManager.isRTL ? 1 : 0];
  return typeof text === 'function' ? text(value) : text;
}
